#!/usr/bin/env bash
# nlqdb — mirror credentials from .envrc to the apps/api Cloudflare
# Worker runtime. Two modes:
#
#   local   → write apps/api/.dev.vars from .envrc (gitignored,
#              read by `wrangler dev`).
#   remote  → push to the deployed Worker via `wrangler secret bulk`
#              (one atomic call, idempotent — overwrites on re-run).
#
# Filters .envrc to the Worker-runtime subset — what apps/api actually
# reads at request time today (Slices 4 + 5). Secrets for slices not
# yet shipped (Stripe webhook, Resend, Upstash, etc.) are intentionally
# skipped here AND the canonical SECRETS array stays in sync with
# scripts/mirror-secrets-gha.sh as those slices land.
#
# Never logs values; only secret names + lengths + OK/skip status.
#
# `GRAFANA_OTLP_AUTHORIZATION` is computed from
# `GRAFANA_CLOUD_INSTANCE_ID:GRAFANA_CLOUD_API_KEY` (Basic auth) so
# rotation stays on the pair, per IMPLEMENTATION §2.6.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

MODE="${1:-}"
case "$MODE" in
  local|remote) ;;
  *)
    echo "Usage: $0 local|remote" >&2
    echo "  local   write apps/api/.dev.vars from .envrc (for wrangler dev)" >&2
    echo "  remote  push to deployed Worker via wrangler secret bulk" >&2
    exit 2
    ;;
esac

say()  { printf '\n\033[1;34m== %s ==\033[0m\n' "$*"; }
ok()   { printf '  \033[1;32m✓\033[0m %s\n' "$*"; }
fail() { printf '  \033[1;31m✗\033[0m %s — %s\n' "$1" "$2"; }
skip() { printf '  \033[2m· skip %s (not set in .envrc)\033[0m\n' "$*"; }

# --- preflight ----------------------------------------------------------
[[ -f .envrc ]] || { fail "preflight" ".envrc not found at $REPO_ROOT — run scripts/bootstrap-dev.sh first"; exit 1; }
command -v jq >/dev/null 2>&1 || { fail "preflight" "jq not installed — brew install jq"; exit 1; }
command -v base64 >/dev/null 2>&1 || { fail "preflight" "base64 not installed (should be in coreutils)"; exit 1; }
if [[ "$MODE" == "remote" ]]; then
  command -v wrangler >/dev/null 2>&1 || { fail "preflight" "wrangler not installed — bun install"; exit 1; }
fi

# Source .envrc without echoing.
set -a
# shellcheck disable=SC1091
source .envrc
set +a

# --- Worker-runtime subset ----------------------------------------------
# What apps/api reads from c.env today. Add new entries here AND in
# apps/api/src/env.d.ts simultaneously so types and runtime stay aligned.
# Order matches .env.example for easy diff.
SECRETS=(
  BETTER_AUTH_SECRET
  CLOUDFLARE_ACCOUNT_ID
  CF_AI_TOKEN
  DATABASE_URL
  GEMINI_API_KEY
  GROQ_API_KEY
  OPENROUTER_API_KEY
  OAUTH_GITHUB_CLIENT_ID
  OAUTH_GITHUB_CLIENT_SECRET
  OAUTH_GITHUB_CLIENT_ID_DEV
  OAUTH_GITHUB_CLIENT_SECRET_DEV
  GOOGLE_CLIENT_ID
  GOOGLE_CLIENT_SECRET
  GRAFANA_OTLP_ENDPOINT
)

# Compute GRAFANA_OTLP_AUTHORIZATION from the instance + key pair.
# .envrc stores them separately for rotation independence; the Worker
# reads the assembled Basic-auth header. Empty string if either half
# is missing — Worker skips OTel install in that case (apps/api/src/index.ts).
GRAFANA_OTLP_AUTHORIZATION=""
if [[ -n "${GRAFANA_CLOUD_INSTANCE_ID:-}" && -n "${GRAFANA_CLOUD_API_KEY:-}" ]]; then
  encoded=$(printf '%s:%s' "$GRAFANA_CLOUD_INSTANCE_ID" "$GRAFANA_CLOUD_API_KEY" | base64 | tr -d '\n')
  # shellcheck disable=SC2034 # read indirectly via "${!name:-}" in the SECRETS loop
  GRAFANA_OTLP_AUTHORIZATION="Basic $encoded"
fi
SECRETS+=(GRAFANA_OTLP_AUTHORIZATION)

# Collect (name, value) pairs. Empty values get skipped, not pushed —
# pushing an empty string would mask a real value already on the Worker.
declare -a names
declare -a values
set_count=0
skip_count=0
for name in "${SECRETS[@]}"; do
  val="${!name:-}"
  if [[ -z "$val" ]]; then
    skip "$name"
    skip_count=$((skip_count + 1))
    continue
  fi
  names+=("$name")
  values+=("$val")
  set_count=$((set_count + 1))
done

# --- local mode ---------------------------------------------------------
if [[ "$MODE" == "local" ]]; then
  say "Writing apps/api/.dev.vars from .envrc"
  out="apps/api/.dev.vars"
  tmp=$(mktemp)
  trap 'rm -f "$tmp"' EXIT
  {
    echo "# Generated by scripts/mirror-secrets-workers.sh local"
    echo "# DO NOT EDIT — re-run the script after .envrc rotation."
    echo "# Gitignored. wrangler dev overlays this on top of [vars] in wrangler.toml."
    echo "NODE_ENV=development"
    for i in "${!names[@]}"; do
      printf '%s=%s\n' "${names[$i]}" "${values[$i]}"
    done
  } > "$tmp"
  mv "$tmp" "$out"
  trap - EXIT
  for name in "${names[@]}"; do
    val="${!name}"
    ok "$name (${#val} chars)"
  done
  echo ""
  say "Done"
  ok "$set_count secrets written to apps/api/.dev.vars (NODE_ENV=development)"
  [[ $skip_count -gt 0 ]] && printf '  \033[2m· %d skipped (empty in .envrc — provision later)\033[0m\n' "$skip_count"
  echo ""
  echo "Run: bun --cwd apps/api run dev"
fi

# --- remote mode --------------------------------------------------------
if [[ "$MODE" == "remote" ]]; then
  say "Pushing to Cloudflare Workers (nlqdb-api) via wrangler secret bulk"
  # Build JSON via jq's $ARGS.named — values arrive through fd-passed
  # --arg, never through argv. One wrangler call atomically updates all
  # secrets; partial failures roll back as a unit.
  declare -a jq_args
  for i in "${!names[@]}"; do
    jq_args+=(--arg "${names[$i]}" "${values[$i]}")
  done
  json=$(jq -n "${jq_args[@]}" '$ARGS.named')
  if printf '%s' "$json" | (cd apps/api && wrangler secret bulk) >/dev/null; then
    for name in "${names[@]}"; do
      val="${!name}"
      ok "$name (${#val} chars)"
    done
    echo ""
    say "Done"
    ok "$set_count secrets pushed to Worker nlqdb-api"
    [[ $skip_count -gt 0 ]] && printf '  \033[2m· %d skipped (empty in .envrc — provision later)\033[0m\n' "$skip_count"
    echo ""
    echo "Verify with: (cd apps/api && wrangler secret list)"
  else
    fail "wrangler secret bulk" "see error above; check CLOUDFLARE_API_TOKEN scope + wrangler login"
    exit 1
  fi
fi
